# Site settings
title1: "CS 269 "
title2: "Seminar: Machine Learning in Natural Language Processing"
email:  ml17@kwchang.net
#description: "Seminar: Current Topics in Artificial Intelligence: Machine Learning in Natural Language Processing"
baseurl: "/CS269-17"
url: "http://uclanlp.github.io/CS269-17"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

