# Site settings
title1: "CS 146"
title2: "Seminar: Machine Learning in Natural Language Processing"
email:  ml17@kwchang.net
#description: "Seminar: Current Topics in Artificial Intelligence: Machine Learning in Natural Language Processing"
baseurl: "/CSM146-18W"
url: "http://uclanlp.github.io/CSM146-18W"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

